;; (setq nano-font-family-monospaced "Hack Nerd Font Mono")
;; (setq nano-font-family-monospaced "Fira Mono")
;; (setq nano-font-family-monospaced "DejaVu Sans Mono")
;; (setq nano-font-family-monospaced "Roboto Mono")
;; (setq my/font "DejaVu Sans Mono")
;; (setq my/font "Fira Mono")
;; (setq my/font "Roboto Mono")
;; (setq my/font "Hack Nerd Font Mono")
;; (set-face-attribute 'default nil :font my/font)
;; (set-frame-font my/font nil t)
;; (nano-refresh-theme)
;; C-u C-x C-e
;; (font-family-list)
